apiVersion: apps/v1
kind: Deployment
metadata:
  name: week1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week1
  template:
    metadata:
      labels:
        app: week1
    spec:
      containers:
      - name: week1
        image: oleksandran/devops-learning:1.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: week1-service
spec:
  selector:
    app: week1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
